client_config_backend: settings
client_config:
  client_id: 44114923952-l30fj0rnu019hfvmhh077mfur1e562sk.apps.googleusercontent.com
  client_secret: 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
 
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
 
get_refresh_token: True
 
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install